helm cleanup for flyte-core
flyteorg/flyte pull request #1398
Opened 2021-08-31 14:53 UTC by evalsocket

- Added Redis config in `userSetting` of eks
- Remove unwanted plugins in core

2021-08-31 16:13 UTC, EngHabu approved these changes

2021-08-31 16:14 UTC, EngHabu requested changes

2021-08-31 16:14 UTC, EngHabu commented on charts/flyte-core/values-eks.yaml
> +        type:
Why is type empty?

2021-08-31 16:37 UTC, evalsocket commented on charts/flyte-core/values-eks.yaml
> +        type:
it should be redis

2021-09-01 10:37 UTC, pmahindrakar-oss submitted a review, later dismissed

2021-09-01 18:21 UTC, EngHabu commented on charts/flyte-core/values.yaml
> +        type: redis
I think the default one shouldn't rely on redis... it should just be `noop`
https://github.com/flyteorg/flytepropeller/blob/eaf084934de5d630cd4c11aae15ecae780cc787e/pkg/controller/nodes/task/resourcemanager/config/config.go#L14

2021-09-01 20:58 UTC, merged