Fixed bug for incorrect name
flyteorg/flyte pull request #4175
Opened 2023-10-05 08:14 UTC by Virtual4087

Closes #4174 

## Tracking issue

## Describe your changes

## Check all the applicable boxes 

- [ ] I updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] All commits are signed-off.

## Screenshots

## Note to reviewers

2023-10-05 09:42 UTC, samhita-alla commented
@kumare3, do you think this PR can be merged?

2023-10-05 19:13 UTC, kumare3 commented on flyteadmin/pkg/manager/impl/validation/execution_validator.go
> +		return errors.NewFlyteAdminErrorf(codes.InvalidArgument, "invalid %s format: %s, does not match regex '^[a-z][a-z\-0-9]*$'", fieldName, executionID)
can we not copy paste the regex, instead print the regex value itself.
Also, update the unit tests

2023-10-06 02:24 UTC, Virtual4087 commented
umm is it okay now?

2023-10-06 13:52 UTC, kumare3 commented
Lgtm

2023-10-06 13:56 UTC, Virtual4087 commented
while you're at it can you add the hacktoberfest label as well?

2023-10-06 14:19 UTC, Virtual4087 commented
can you share the test location? I'll update it

2023-10-06 14:23 UTC, Virtual4087 commented
I'm not familiar with these tests so i couldn't find it but the changes work well. The test just needs to be updated

2023-10-06 16:57 UTC, Virtual4087 commented
i think it's good now

2023-10-08 02:39 UTC, pingsutw approved these changes

2023-10-08 03:03 UTC, pingsutw requested changes
Test is failing.
```
        	Error Trace:	/home/runner/work/flyte/flyte/flyteadmin/pkg/manager/impl/validation/execution_validator_test.go:45
        	Error:      	Error message not equal:
        	            	expected: "invalid name format: 12345"
        	            	actual  : "invalid name format: 12345, does not match regex '^[a-z][a-z\\-0-9]*$'"

```

2023-10-08 03:33 UTC, Virtual4087 commented
Ok it should work now i updated the test

2023-10-09 08:55 UTC, samhita-alla commented
@Virtual4087, I'll add the hacktoberfest-accepted label once the PR is merged.

2023-10-09 11:41 UTC, Virtual4087 commented
I think you guys need to update the unit test for the checks to be successful. The test expects "invalid name format: 12345" but you asked to make it ""invalid name format: 12345, does not match regex '^[a-z][a-z\\-0-9]*$'". I've also updated the tests on my branch so kindly check the pr once.

2023-10-09 21:06 UTC, pingsutw reviewed
Line 173 and 176 need to be updated as well. https://github.com/flyteorg/flyte/blob/4a780c30809d713a8e03417f6ffbc6674960bbc1/flyteadmin/pkg/manager/impl/validation/execution_validator_test.go#L173-L176

2023-10-10 05:55 UTC, Virtual4087 commented
> Line 173 and 176 need to be updated as well.
> 
> https://github.com/flyteorg/flyte/blob/4a780c30809d713a8e03417f6ffbc6674960bbc1/flyteadmin/pkg/manager/impl/validation/execution_validator_test.go#L173-L176

Done

2023-10-12 06:54 UTC, samhita-alla commented
@pingsutw, could you please review this PR now?

2023-10-12 06:58 UTC, pingsutw approved these changes
LGTM

2023-10-12 06:59 UTC, merged

2023-10-12 07:09 UTC, Virtual4087 commented
Finally