[DOC] Update agent API
flyteorg/flyte pull request #4943
Opened 2024-02-24 01:19 UTC by pingsutw

Update agent API and example in the Doc

https://flyte--4943.org.readthedocs.build/en/4943/flyte_agents/testing_agents_locally.html

2024-02-24 01:55 UTC, Future-Outlier commented on docs/flyte_agents/developing_agents.md
> +        super().__init__(task_type_name="saprk", metadata_type=BigQueryMetadata)
```suggestion
        super().__init__(task_type_name="bigquery", metadata_type=BigQueryMetadata)
```

2024-02-24 01:56 UTC, Future-Outlier commented on docs/flyte_agents/developing_agents.md
> +To create a new async agent, extend the `SyncAgentBase` class and implement `do` methods. This method need to be idempotent.
```suggestion
To create a new sync agent, extend the `SyncAgentBase` class and implement `do` methods. This method needs to be idempotent.
```

2024-02-24 16:30 UTC, neverett requested changes
Some small edits requested, otherwise looks great, thanks for adding this!

2024-02-24 16:30 UTC, neverett commented on docs/flyte_agents/developing_agents.md
> +To create a new async agent, extend the `AsyncAgentBase` and implement `create`, `get`, and `delete` methods. These methods need to be idempotent.
```suggestion
To create a new async agent, extend the `AsyncAgentBase` and implement `create`, `get`, and `delete` methods. These methods must be idempotent.
```

2024-02-24 16:30 UTC, neverett commented on docs/flyte_agents/developing_agents.md
> +To create a new async agent, extend the `SyncAgentBase` class and implement `do` methods. This method need to be idempotent.
```suggestion
To create a new sync agent, extend the `SyncAgentBase` class and implement a `do` method. This method must be idempotent.
```

2024-02-24 16:30 UTC, neverett commented on docs/flyte_agents/testing_agents_locally.md
> +Adding `AsyncAgentExecutorMixin` to this class to tell flytekit to use the agent to run the task.
```suggestion
Add `AsyncAgentExecutorMixin` to this class to tell flytekit to use the agent to run the task.
```

2024-02-24 16:30 UTC, neverett commented on docs/flyte_agents/testing_agents_locally.md
> +To execute the Spark task on the agent, it's essential to configure the raw-output-data-prefix with a remote path.
```suggestion
To execute the Spark task on the agent, you must configure the `raw-output-data-prefix` with a remote path.
```

2024-02-24 16:30 UTC, neverett commented on docs/flyte_agents/testing_agents_locally.md
> +This configuration ensures that Flytekit transfers the input data to the blob storage.
```suggestion
This configuration ensures that flytekit transfers the input data to the blob storage and allows the Spark job running on Databricks to access the input data directly from the designated bucket.
```

2024-02-24 16:30 UTC, neverett commented on docs/flyte_agents/testing_agents_locally.md
> +Consequently, the Spark job running on Databricks can access the input data directly from the designated bucket.
```suggestion

```

2024-02-24 16:30 UTC, neverett commented on docs/flyte_agents/testing_agents_locally.md
> +The Spark task will run locally if the raw-output-data-prefix is not set.
```suggestion
The Spark task will run locally if the `raw-output-data-prefix` is not set.
```

2024-02-28 17:37 UTC, neverett approved these changes

2024-02-28 18:18 UTC, merged