docs(troubleshoot): Add docker error troubleshooting guide
flyteorg/flyte pull request #4972
Opened 2024-02-28 15:01 UTC by MortalHappiness

## Tracking issue
N/A

## Why are the changes needed?

Some users like me encountered the docker error while trying to start Flyte.

![Untitled](https://github.com/flyteorg/flyte/assets/47914085/175f8090-5dcf-4a32-9143-4bf157e2397d)

## What changes were proposed in this pull request?

Add troubleshooting guide for docker error.

## How was this patch tested?

### Setup process

### Screenshots

## Check all the applicable boxes 

- [x] I updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Related PRs

## Docs link

2024-02-29 00:53 UTC, pingsutw submitted a review, later dismissed
Thank you!

2024-02-29 15:36 UTC, neverett requested changes
A few small changes requested, otherwise looks good. Thanks!

2024-02-29 15:36 UTC, neverett commented on docs/community/troubleshoot.rst
> +This error will show if your are not running Docker with the native Docker engine in a Linux machine. Most probably you are running Docker via Docker Desktop.
```suggestion
This error will show if you are not running Docker with the native Docker engine in a Linux machine. Most likely you are running Docker via Docker Desktop.
```

2024-02-29 15:36 UTC, neverett commented on docs/community/troubleshoot.rst
> +- If you are using Docker Desktop in MacOs, run
```suggestion
- If you are using Docker Desktop in MacOS, run:
```

2024-02-29 15:36 UTC, neverett commented on docs/community/troubleshoot.rst
> +- If you are using Docker Desktop in Linux, run
```suggestion
- If you are using Docker Desktop in Linux, run:
```

2024-02-29 15:36 UTC, neverett commented on docs/community/troubleshoot.rst
> +- If you are using some other tools to run Docker, you need to make sure that ``/var/run/docker.sock`` is linked to the correct socket file.
```suggestion
- If you are using another tool to run Docker, make sure that ``/var/run/docker.sock`` is linked to the correct socket file.
```

2024-02-29 15:36 UTC, neverett commented on docs/community/troubleshoot.rst
> +  For example, if you are using Rancher Desktop on Linux, run
```suggestion
  For example, if you are using Rancher Desktop on Linux, run:
```

2024-02-29 15:48 UTC, MortalHappiness commented
@neverett Fixed. Thank you.

2024-02-29 23:54 UTC, pingsutw approved these changes
Thank you @neverett @MortalHappiness

2024-03-29 08:55 UTC, pingsutw approved these changes

2024-04-07 05:27 UTC, pingsutw approved these changes

2024-04-08 14:14 UTC, neverett approved these changes

2024-04-08 14:14 UTC, merged