[Docs] Chatgpt Agent Setup
flyteorg/flyte pull request #4992
Opened 2024-03-02 00:38 UTC by Future-Outlier

## Docs link

## Tracking issue
https://github.com/flyteorg/flyte/issues/3936

## Why are the changes needed?

## What changes were proposed in this pull request?

## How was this patch tested?

### Setup process

### Screenshots

## Check all the applicable boxes 

- [x] I updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] All commits are signed-off.

## Related PRs

2024-03-04 07:01 UTC, Future-Outlier commented
I fail to build docs in my local environments too.
<img width="799" alt="image" src="https://github.com/flyteorg/flyte/assets/76461262/f901a46a-f4b0-43ea-9486-cd24868994ca">

2024-03-04 20:10 UTC, neverett requested changes
A few changes requested, otherwise looks good, thanks for adding this!

2024-03-04 20:10 UTC, neverett commented on docs/deployment/agents/chatgpt.rst
> +Chatgpt agent
```suggestion
ChatGPT agent
```

2024-03-04 20:10 UTC, neverett commented on docs/deployment/agents/chatgpt.rst
> +This guide provides an overview of how to set up the Chatgpt agent in your Flyte deployment.
```suggestion
This guide provides an overview of how to set up the ChatGPT agent in your Flyte deployment.
```

2024-03-04 20:10 UTC, neverett commented on docs/deployment/agents/chatgpt.rst
> +Please note that you have to setup the openai api key in the agent server to to run the Chatgpt tasks.
```suggestion
Please note that you have to set up the OpenAI API key in the agent server to to run ChatGPT tasks.
```

2024-03-04 20:10 UTC, neverett commented on docs/deployment/agents/chatgpt.rst
> +      Create a file named ``values-override.yaml`` and add the following configuration to it.
```suggestion
      Create a file named ``values-override.yaml`` and add the following configuration to it:
```

2024-03-04 20:10 UTC, neverett commented on docs/deployment/agents/chatgpt.rst
> +Add the OPENAI API token
```suggestion
Add the OpenAI API token
```

2024-03-04 20:10 UTC, neverett commented on docs/deployment/agents/chatgpt.rst
> +You have to set the Databricks token to the Flyte configuration.
Should this be removed?

2024-03-04 20:10 UTC, neverett commented on docs/deployment/agents/chatgpt.rst
> +1. Install flyteagent pod using helm
```suggestion
1. Install flyteagent pod using helm:
```

2024-03-04 20:10 UTC, neverett commented on docs/deployment/agents/chatgpt.rst
> +2. Get the base64 value of your OPENAI API token.
```suggestion
2. Get the base64 value of your OPENAI API token:
```

2024-03-04 20:10 UTC, neverett commented on docs/deployment/agents/chatgpt.rst
> +3. Edit the flyteagent secret
```suggestion
3. Edit the flyteagent secret:
```

2024-03-04 20:10 UTC, neverett commented on docs/deployment/agents/chatgpt.rst
> +For Chatgpt agent on the Flyte cluster, see `Chatgpt agent <https://docs.flyte.org/en/latest/flytesnacks/examples/chatgpt_agent/index.html>`_.
```suggestion
For ChatGPT agent on the Flyte cluster, see `ChatGPT agent <https://docs.flyte.org/en/latest/flytesnacks/examples/chatgpt_agent/index.html>`_.
```

2024-03-04 20:10 UTC, neverett commented on docs/deployment/agents/index.md
> +* - {ref}`ChatGPT Agent <deployment-agent-setup-databricks>`
```suggestion
* - {ref}`ChatGPT Agent <deployment-agent-setup-chatgpt>`
```

2024-03-05 00:05 UTC, Future-Outlier commented on docs/deployment/agents/chatgpt.rst
> +You have to set the Databricks token to the Flyte configuration.
yes, thank you

2024-03-05 15:18 UTC, neverett approved these changes

2024-03-05 23:51 UTC, pingsutw approved these changes

2024-03-05 23:51 UTC, merged