Use flytectl demo to run integration tests
flyteorg/flyte pull request #5034
Opened 2024-03-10 12:05 UTC by pingsutw

## Tracking issue
NA

## Why are the changes needed?
We're going to remove `flytectl sandbox start`

## What changes were proposed in this pull request?
Use flytectl demo to run integration tests

## How was this patch tested?

### Setup process

### Screenshots

## Check all the applicable boxes 

- [ ] I updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] All commits are signed-off.

## Related PRs
https://github.com/flyteorg/flytectl/pull/462

## Docs link

2024-03-12 01:11 UTC, eapolinario commented
I'm 99% sure we don't use this workflow anywhere. Can you double-check and if that's the case, should we remove it?

2024-05-06 12:25 UTC, pingsutw commented
@eapolinario I revive end2end test. It only runs when merging PRs since it takes 15 minutes.

https://github.com/flyteorg/flyte/actions/runs/8967710966/job/24626449666?pr=5034

2024-05-06 16:09 UTC, pingsutw commented on boilerplate/flyte/end2end/run-tests.py
> +    default=False,
Run flytesnacks workflow serially in the CI due to disk pressure in the sandbox.

2024-05-07 22:06 UTC, eapolinario approved these changes
That's pretty cool. Thank you!

2024-05-08 00:50 UTC, eapolinario requested changes

2024-05-08 00:50 UTC, eapolinario commented on .github/workflows/end2end.yml
> +          flytectl demo start --source=$(pwd) --image ghcr.io/${{ github.repository_owner }}/flyte-sandbox-bundled:latest --disable-agent
just to confirm, where is this image built?

2024-05-08 03:00 UTC, pingsutw commented on .github/workflows/single-binary.yml
> +    needs: [ build-and-push-sandbox-bundled-image ]
@eapolinario here. after `build-and-push-sandbox-bundled-image`

2024-05-08 03:03 UTC, eapolinario submitted a review, later dismissed

2024-05-08 14:52 UTC, eapolinario approved these changes

2024-05-09 11:46 UTC, pingsutw commented
Just found that we already have end2end tests [here](https://github.com/flyteorg/flyte/blob/faf8fc8153b3e0ac039c300ceab31c54be537985/.github/workflows/single-binary.yml#L200), so we don't need `end2end.yml` anymore

2024-06-16 01:04 UTC, Future-Outlier approved these changes

2024-06-16 01:35 UTC, eapolinario approved these changes

2024-06-16 01:35 UTC, merged