Re-apply changes  to dataclass docs from flytesnacks#1553
flyteorg/flyte pull request #5211
Opened 2024-04-10 14:40 UTC by neverett

## Why are the changes needed?

The user guide docs have been moved to Flyte, so we need to re-apply changes from https://github.com/flyteorg/flytesnacks/pull/1553/.

## Check all the applicable boxes 

- [ ] I updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] All commits are signed-off.

## Related PRs

https://github.com/flyteorg/flytesnacks/pull/1553/

## Docs link

TK

2024-04-10 20:56 UTC, pingsutw approved these changes

2024-04-11 01:45 UTC, Future-Outlier requested changes
We need to put the notes into the `important` section, not out of it.

<img width="776" alt="image" src="https://github.com/flyteorg/flyte/assets/76461262/c848fc03-46ed-4286-a9ad-c2069266c53b">

2024-04-11 19:26 UTC, neverett commented
@Future-Outlier fixed!

2024-04-12 03:40 UTC, Future-Outlier approved these changes
LGTM, thank you

<img width="757" alt="image" src="https://github.com/flyteorg/flyte/assets/76461262/7a603a30-03a3-4b85-846a-33949be6896d">

2024-04-12 03:40 UTC, merged