initial commit
flyteorg/flyte pull request #5839
Opened 2024-10-10 10:58 UTC by aazam-gh

## Tracking issue

Fixes #5738

## Why are the changes needed?

In order to ensure that this [example](https://docs.flyte.org/en/latest/flytesnacks/examples/ray_plugin/index.html) is reproducible.

## What changes were proposed in this pull request?

Updating `index.rst` under docs/deployment/plugins

## How was this patch tested?

### Setup process

### Screenshots

## Check all the applicable boxes 

- [x] I updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] All commits are signed-off.

## Related PRs

## Docs link

2024-10-10 23:08 UTC, wild-endeavor commented
@aazam-gh thanks for the pr.  will let @davidmirror-ops comment on this when he's back next week, but this pr looks good.  You tested the changes in demo cluster?

Also this pr doesn't close out the entire issue right? There's a couple other changes it needs?

2024-10-11 15:12 UTC, aazam-gh commented
Yes this pr does need to include more changes. I have not tested it yet, will do !

2025-01-07 19:23 UTC, davidmirror-ops commented on docs/deployment/plugins/k8s/index.rst
> +                  rbac:
```suggestion
```

2025-01-07 19:27 UTC, davidmirror-ops requested changes
@aazam-gh thanks for contributing and really sorry about the delays.

This is the relevant section that has to be updated: https://github.com/flyteorg/flyte/blob/27c9edde18c67b51a6ea22441ff6a96c5a9482f0/docs/deployment/plugins/k8s/index.rst?plain=1#L252-L304

Let me know if you need help

Thanks

2025-01-07 19:27 UTC, davidmirror-ops commented on docs/deployment/plugins/k8s/index.rst
> +                  rbac:
@aazam-gh Please remove this whole section as it belongs to Spark config, which is not the focus of the issue

2025-01-07 19:27 UTC, davidmirror-ops commented on docs/deployment/plugins/k8s/index.rst
> +                  rbac:
```suggestion
```
Same here, this section is not Ray but Spark. Please remove

2025-01-07 19:27 UTC, davidmirror-ops commented on docs/deployment/plugins/k8s/index.rst
> +                  rbac:
```suggestion
```

2025-01-07 19:27 UTC, davidmirror-ops commented on docs/deployment/plugins/k8s/index.rst
> +                  rbac:
```suggestion
```

2025-01-23 22:41 UTC, closed without merging