[WIP] Reference task to fetch latest version by default
flyteorg/flyte pull request #5895
Opened 2024-10-23 09:44 UTC by featherchen

## Tracking issue

Related to #5825 
## Why are the changes needed?

When task version is not specified (i.e. ""), we should return the latest one when `getTask` is called
## What changes were proposed in this pull request?

## How was this patch tested?

### Setup process

### Screenshots

## Check all the applicable boxes 

- [ ] I updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] All commits are signed-off.

## Related PRs

## Docs link

2024-10-25 20:00 UTC, eapolinario commented
`TesGetTask` is [failing](https://github.com/flyteorg/flyte/actions/runs/11512104582/job/32076880676?pr=5895#step:4:470), can you take a look?

2024-10-28 10:50 UTC, featherchen commented
@eapolinario TestGetTask should work now, thanks @troychiu for the fix.

2024-11-15 12:51 UTC, featherchen commented
@troychiu Can you help me review this PR? Thanks.

2024-11-26 01:05 UTC, pingsutw approved these changes

2024-11-26 01:05 UTC, pingsutw commented on flyteadmin/pkg/repositories/gormimpl/task_repo.go
> +		tx = r.db.WithContext(ctx).Where(`"tasks"."project" = ? AND "tasks"."domain" = ? AND "tasks"."name" = ?`, input.Project, input.Domain, input.Name).Limit(1)
Just curious, are we able to use TaskKey here?
```golang
models.TaskKey{
  Project: input.Project,
  Domain:  input.Domain,
  Name:    input.Name,
}
```

2024-11-26 01:12 UTC, troychiu commented on flyteadmin/pkg/repositories/gormimpl/task_repo.go
> +		tx = tx.Order(`"tasks"."version" DESC`)
Why do we order by version instead of time information such as created_at?

2024-11-26 01:12 UTC, troychiu commented on flyteadmin/tests/task_execution_test.go
> +func TestGetTaskExecutions(t *testing.T) {
Can we register more than one tasks and see if we get the latest one?

2024-12-02 03:33 UTC, Future-Outlier commented
cc @featherchen ?

2024-12-02 03:33 UTC, Future-Outlier requested changes
let's wait for the update

2025-01-02 15:17 UTC, Future-Outlier commented
@featherchen any update?

2025-03-03 19:12 UTC, eapolinario commented
Cleaning stale PRs. Please reopen if you wan to discuss this further.

2025-03-03 19:12 UTC, closed without merging